name: Deploy front (Docker)

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: namturne/weatherpick-front:latest

      - name: SSH and deploy front container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.209.68.253
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[1] Stop old container"
            docker stop weatherpick-container || true
            docker rm weatherpick-container || true

            echo "[2] Pull latest image from Docker Hub"
            docker pull namturne/weatherpick-front:latest

            echo "[3] Run new container"
            docker run -d -p 443:3000 --name weatherpick-front weatherpick-front:latest
